# Generated by Django 3.2.5 on 2022-02-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [

        migrations.CreateModel(
            name='QuestionsModel',
            fields=[
                ('questionary_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('job', models.CharField(max_length=2)),
                ('instant_coffee', models.IntegerField()),
                ('grain_coffee', models.IntegerField()),
                ('tea', models.IntegerField()),
                ('energy_drinks', models.IntegerField()),
                ('pills', models.IntegerField()),
                ('addiction1', models.IntegerField()),
                ('addiction2', models.IntegerField()),
                ('addiction3', models.IntegerField()),
                ('symptoms', models.CharField(max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('is_staff', models.BooleanField(default=False))
            ],
        ),
    ]
